Controllers/KemgresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SGK.Models;

namespace SGK.Controllers
{
    public class KemgresController : Controller
    {
        private readonly ModelContext _context;

        public KemgresController(ModelContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Graph()
        {
              return View(await _context.Kemgres.ToListAsync());
        }
    }
}

Controllers/KemtecMinsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SGK.Models;

namespace SGK.Controllers
{
    public class KemtecMinsController : Controller
    {
        private readonly ModelContext _context;

        public KemtecMinsController(ModelContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Graph()
        {
              return View(await _context.KemtecMins.ToListAsync());
        }
    }
}

Controllers/KemtecsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SGK.Models;

namespace SGK.Controllers
{
    public class KemtecsController : Controller
    {
        private readonly ModelContext _context;

        public KemtecsController(ModelContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Graph()
        {
              return View(await _context.Kemtecs.ToListAsync());
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SGK</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SGK.styles.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">
</head>
<body>
    <div class="header">
        <div class="logo-img logo-img-bgc">
            <img src="~/image/SGK_logo.svg" class="logo" />
        </div>
        <div class="header__menu">
            <div class="menu__btn">
                @switch (ViewData["Title"])
                {
                    case "Кемеровская ГРЭС Почасовая температура":
                        <a class="btn__time"asp-area="" asp-controller="KemgresMins" asp-action="Graph">По минутам</a>
                        break;
                    case "Кемеровская ТЭЦ Почасовая температура":
                        <a class="btn__time"asp-area="" asp-controller="KemtecMins" asp-action="Graph">По минутам</a>
                        break;
                    case "Ново-Кемеровская ТЭЦ Почасовая температура":
                        <a class="btn__time"asp-area="" asp-controller="NewkemtecMins" asp-action="Graph">По минутам</a>
                        break;
                    case "Беловская ГРЭС Почасовая температура":
                        <a class="btn__time"asp-area="" asp-controller="BelovskayagresMins" asp-action="Graph">По минутам</a>
                        break;
                    case "Томь-Усинская ГРЭС Почасовая температура":
                        <a class="btn__time"asp-area="" asp-controller="TomusinskaygresMins" asp-action="Graph">По минутам</a>
                        break;
                    case "ГТЭС Новокузнецкая Почасовая температура":
                        <a class="btn__time"asp-area="" asp-controller="GtesnovokuznetckayMins" asp-action="Graph">По минутам</a>
                        break;
                    case "Кузнецкая ТЭЦ Почасовая температура":
                        <a class="btn__time"asp-area="" asp-controller="KuznetckaytecMins" asp-action="Graph">По минутам</a>
                        break;
                    case "Кемеровская ГРЭС Минутная температура":
                        <a class="btn__time"asp-area="" asp-controller="Kemgres" asp-action="Graph">По часам</a>
                        break;
                    case "Кемеровская ТЭЦ Минутная температура":
                        <a class="btn__time"asp-area="" asp-controller="Kemtecs" asp-action="Graph">По часам</a>
                        break;
                    case "Ново-Кемеровская ТЭЦ Минутная температура":
                        <a class="btn__time"asp-area="" asp-controller="Newkemtecs" asp-action="Graph">По часам</a>
                        break;
                    case "Беловская ГРЭС Минутная температура":
                        <a class="btn__time"asp-area="" asp-controller="Belovskayagres" asp-action="Graph">По часам</a>
                        break;
                    case "Томь-Усинская ГРЭС Минутная температура":
                        <a class="btn__time"asp-area="" asp-controller="Tomusinskaygres" asp-action="Graph">По часам</a>
                        break;
                    case "ГТЭС Новокузнецкая Минутная температура":
                        <a class="btn__time"asp-area="" asp-controller="Gtesnovokuznetckays" asp-action="Graph">По часам</a>
                        break;
                    case "Кузнецкая ТЭЦ Минутная температура":
                        <a class="btn__time"asp-area="" asp-controller="Kuznetckaytecs" asp-action="Graph">По часам</a>
                        break;
                }
            </div>
        </div>
    </div>
    <hr class="header__line">
    <div id="graphic" class="graphic">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div class="left_menu">
        <div class="grap-btn grap-btn-bgc">
            <nav class="left_menu-nav menu_nav">
                <a class="graph_btn graph_btn-text" asp-area="" asp-controller="Kemgres" asp-action="Graph">Кемеровская ГРЭС</a>
                <a class="graph_btn graph_btn-text" asp-area="" asp-controller="Kemtecs" asp-action="Graph">Кемеровская ТЭЦ</a>
                <a class="graph_btn " asp-area="" asp-controller="Newkemtecs" asp-action="Graph">Ново-Кемеровская ТЭЦ</a>
                <a class="graph_btn graph_btn-text" asp-area="" asp-controller="BelovskayaGres" asp-action="Graph">Беловская ГРЭС</a>
                <a class="graph_btn graph_btn-text" asp-area="" asp-controller="Tomusinskaygres" asp-action="Graph">Томь-Усинская ГРЭС</a>
                <a class="graph_btn graph_btn-text" asp-area="" asp-controller="Gtesnovokuznetckays" asp-action="Graph">ГТЭС Новокузнецкая</a>
                <a class="graph_btn graph_btn-text" asp-area="" asp-controller="Kuznetckaytecs" asp-action="Graph">Кузнецкая ТЭЦ</a>
            </nav>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>